sudo: required
language: node_js
cache:
  directories:
    - node_modules
    - ~/.meteor
notifications:
  email:
    recipients:
      - katrotz@gmail.com
    on_success: always
    on_failure: always
node_js:
  - 4.1
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -L http://git.io/ejPSng | /bin/sh
  - npm i -g npm@^2.0.0
  - npm i -g velocity-cli
before_script:
  - export PATH=$HOME/.meteor:$PATH
  - npm prune
script:
  - npm run test:ci
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\\d+\\.\\d+\\.\\d+$/
services:
  - mongodb
